### ISSUE TITLE
core.rb:384:in `parse': undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by mokkin** [danielpetri1/bbb-recording-exporter#15]
I tried out your exporter, but unfortunately I am getting this error:
```
ruby download_client.rb "https://konferenz.xxx.de/playback/presentation/2.3/5720c6560b8ef27d38ce47f35ed76175b78172ce-1620658952093"
Traceback (most recent call last):
	4: from download_client.rb:31:in `<main>'
	3: from download_client.rb:31:in `each'
	2: from download_client.rb:32:in `block in <main>'
	1: from download_client.rb:16:in `download'
/usr/lib/ruby/2.7.0/cgi/core.rb:384:in `parse': undefined method `split' for nil:NilClass (NoMethodError)

```
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
Ubuntu 20.04

**Comment by danielpetri1** [comment]
Thanks for informing me of this. Hadn't considered links in the 2.3 format yet.

In download_client.rb change the first function to this: 

```
def download(file)
  # Format: "https://hostname/presentation/meetingID/file"

  # path = "https://balancer.bbb.rbg.tum.de/presentation/f5c1fdc86039b1cd48cb686d38ec0eb6be27dfc7-1619030802001/"
  path = "https://konferenz.xxx.de/presentation/5720c6560b8ef27d38ce47f35ed76175b78172ce-1620658952093/" + file


  puts "Downloading #{path}"

  File.open(file, 'wb') do |get|
    get << URI.parse(path.to_s).open(&:read)
  end
end
```
