### ISSUE TITLE
render whiteboard error

### ISSUE THREAD

**Issue by mokkin** [danielpetri1/bbb-recording-exporter#21]
while `ruby render_cursor.rb` & `ruby render_chat.rb` are successfull `ruby render_whiteboard.rb` throws an error:
```
ruby render_whiteboard.rb
Traceback (most recent call last):
	4: from render_whiteboard.rb:39:in `<main>'
	3: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:154:in `xpath'
	2: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:179:in `xpath_internal'
	1: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:198:in `xpath_impl'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/searchable.rb:198:in `evaluate': ERROR: Undefined namespace prefix: //xmlns:g/xmlns:switch/xmlns:foreignObject (Nokogiri::XML::XPath::SyntaxError)

```

**Comment by danielpetri1** [comment]
Does it work if you change line 39 to 

`xhtml = @doc.xpath('//xmlns:g/xmlns:switch/xmlns:foreignObject', 'xmlns' => 'http://www.w3.org/2000/svg')` ?

**Comment by mokkin** [comment]
Indeed it does!
