### ISSUE TITLE
"is a directory" on pdf-export and client-side branches

### ISSUE THREAD

**Issue by shad00m** [danielpetri1/bbb-recording-exporter#35]
Hey,
on export_slides.rb I'm getting the following:

```
Started exporting PDF
Traceback (most recent call last):
        8: from export_slides.rb:267:in `<main>'
        7: from export_slides.rb:255:in `export_pdf'
        6: from export_slides.rb:44:in `convert_whiteboard_shapes'
        5: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
        4: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
        3: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        2: from export_slides.rb:61:in `block in convert_whiteboard_shapes'
        1: from export_slides.rb:38:in `base64_encode'
export_slides.rb:38:in `read': Is a directory @ io_fread - /home/me/exporterbbb/client/ (Errno::EISDIR)
```

and on export_presentation.rb I get this:

```
Traceback (most recent call last):
        7: from export_presentation.rb:368:in `<main>'
        6: from export_presentation.rb:50:in `convert_whiteboard_shapes'
        5: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
        4: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
        3: from /var/lib/gems/2.7.0/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        2: from export_presentation.rb:66:in `block in convert_whiteboard_shapes'
        1: from export_presentation.rb:44:in `base64_encode'
export_presentation.rb:44:in `read': Is a directory @ io_fread - /home/me/exporterbbb/client/ (Errno::EISDIR)
```

I had to remove "deskshare" from the download as my presentation doesn't have one. FFMPEG is compiled with the required flags set.

**Comment by shad00m** [comment]
recompiling ffmpeg with the "librsvgdec.c" and setting FFMPEG_REFERENCE_SUPPORT to TRUE works now.
I thought it's not mandatory

**Comment by danielpetri1** [comment]
Hi @shad00m,
Thanks for sharing this bug. Yes, it should not be required to recompile ffmpeg with librsvgdec.c .

Can I take a look at the shapes.svg file? It seems like a directory path is being passed to the base64 function, when it should only be receiving file paths.

**Comment by danielpetri1** [comment]
Adding this as the first line in the `base64_encode` method should fix the problem:

 `return "" if File.directory?(path)`
