### ISSUE TITLE
Gem Errors -> cannot export presentation to mp4

### ISSUE THREAD

**Issue by ccomincini** [danielpetri1/bbb-recording-exporter#63]
trying to export a presentation give errors:

>  ./presentation.rb -m b775194a98001f12e1baf8928521943d5923d958-1638800193723

/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Traceback (most recent call last):
	2: from ./presentation.rb:15:in `<main>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- /usr/local/bigbluebutton/core/scripts/lib/recordandplayback (LoadError)

BBB Version:

```
> 
> BigBlueButton Server 2.3.15 (2482)
> 
> ii  bbb-apps-akka                          2.3.0-103                                       all          BigBlueButton Apps (Akka)
> ii  bbb-config                             1:2.3.0-98                                      amd64        BigBlueButton configuration utilities
> ii  bbb-etherpad                           1:2.3.0-52                                      amd64        The EtherPad Lite components for BigBlueButton
> ii  bbb-freeswitch-core                    2:2.3.0-28                                      amd64        BigBlueButton build of FreeSWITCH
> ii  bbb-freeswitch-sounds                  1:1.6.7-3                                       amd64        FreeSWITCH Sounds
> ii  bbb-fsesl-akka                         2.3.0-55                                        all          BigBlueButton FS-ESL (Akka)
> ii  bbb-html5                              1:2.3.0-1854                                    amd64        The HTML5 components for BigBlueButton
> ii  bbb-libreoffice-docker                 1:2.3.0-60                                      amd64        BigBlueButton setup for LibreOffice running in docker
> ii  bbb-mkclean                            1:0.8.7-4                                       amd64        Clean and optimize Matroska and WebM files
> ii  bbb-playback                           1:2.3.0-23                                      amd64        BigBlueButton playback
> ii  bbb-playback-presentation              1:2.3.0-13                                      amd64        BigBluebutton playback of presentation
> ii  bbb-record-core                        1:2.3.0-37                                      amd64        BigBlueButton record and playback
> ii  bbb-web                                1:2.3.0-97                                      amd64        BigBlueButton API
> ii  bbb-webrtc-sfu                         1:2.3.0-37                                      amd64        BigBlueButton WebRTC SFU
> ii  bigbluebutton                          1:2.3.0-7                                       amd64        Open source web conferencing platform (bbb)
> ii  ffmpeg                                 7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        Tools for transcoding, streaming and playing of multimedia files
> ii  libavcodec58:amd64                     7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
> ii  libavdevice58:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for handling input and output devices - runtime files
> ii  libavfilter7:amd64                     7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library containing media filters - runtime files
> ii  libavformat58:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
> ii  libavresample4:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg compatibility library for resampling - runtime files
> ii  libavutil56:amd64                      7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library with functions for simplifying programming - runtime files
> ii  libopusenc0                            0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
> ii  libpostproc55:amd64                    7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for post processing - runtime files
> ii  libswresample3:amd64                   7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
> ii  libswscale5:amd64                      7:4.2.4-1ubuntu0.1bbb2~18.04                    amd64        FFmpeg library for image scaling and various conversions - runtime files
```

**Comment by danielpetri1** [comment]
Hi @ccomincini, did you place the file `presentation.rb` in the post_publish folder?

**Comment by hostbbb** [comment]
have you successfully converted any recordings with this server, or is this an exception with others converting fine?

**Comment by ccomincini** [comment]
> Hi @ccomincini, did you place the file `presentation.rb` in the post_publish folder?

Yes I did.
At the end of a million-failed-test session i rebuilt the bbb server, uninstalling and reinstalling everything and now tjre error is gone .
