### ISSUE TITLE
Manually launching presentation.rb to build mp4 fails

### ISSUE THREAD

**Issue by pielonet** [danielpetri1/bbb-recording-exporter#78]
Hi,

When trying to manually build mp4, I get the following error : 

```
sudo -u bigbluebutton ./post_publish/presentation.rb -m 7db7d35b5a5fbf729334056a3973340ca2c65af9-1642435214658 -f presentation
Traceback (most recent call last):
	2: from ./post_publish/presentation.rb:6:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- builder (LoadError)
```
It looks like the library builder.rb is missing from path.
Is a particular execution environment needed ?

Kind regards,
Thierry

**Comment by danielpetri1** [comment]
Hi Thierry,
Sorry for the wait.

I haven't been able to replicate this issue, but a particular execution environment shouldn't be needed.
Does (re-)installing the builder gem (maybe as the BigBlueButton user) fix the issue?

**Comment by pielonet** [comment]
Hi Daniel,

The following statement worked as expected, using **bundle** (so that ruby uses gems in the local "vendor" directory) in folder `/usr/local/bigbluebutton/core` :

```
sudo -u bigbluebutton bundle exec ruby ./scripts/post_publish/presentation.rb -m 7db7d35b5a5fbf729334056a3973340ca2c65af9-1642435214658 -f presentation
```

Please update your README.md file accordingly !

Kind regards,
Thierry

**Comment by danielpetri1** [comment]
Hi @pielonet,
Glad you got is solved!
Thanks for reaching out again together with the fix, as this will help others out in the community.

Cheers
